services:
  api:
    build: .
    container_name: fastapi_shop_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      PYTHONPATH: /code
    volumes:
      - ./app:/code/app
      - ./tests:/code/tests
      - ./alembic:/code/alembic
      - ./alembic.ini:/code/alembic.ini
      - ./scripts:/code/scripts
      - ./media:/code/media
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: fastapi_shop_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "Passw0rd11"
      POSTGRES_DB: shop_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d shop_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: fastapi_shop_adminer
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
