"""add index on products price_cents

Revision ID: 55c775aee977
Revises: 809c4b1184b7
Create Date: 2026-09-02 08:06:43.709974

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '55c775aee977'
down_revision: str | Sequence[str] | None = '809c4b1184b7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_products_price_cents'), 'products', ['price_cents'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_price_cents'), table_name='products')
    # ### end Alembic commands ###
