"""create categories table

Revision ID: 776253604842
Revises: 3ad7418eab15
Create Date: 2026-08-28 12:31:55.115579

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '776253604842'
down_revision: str | Sequence[str] | None = '3ad7418eab15'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
